### ISSUE TITLE
[Design] Make Index Builder Responsive

### ISSUE THREAD

**Issue by Makosak** [GeoDaCenter/chicago-environment-explorer#150]
**Issue**
need to make index builder responsive/mobile friendly

**Recommendation**

**Rationale**

**Additional context**

**Comment by mradamcox** [comment]
@bodom0015 and I discussed this and I think there are some fairly quick changes to make that would get us far along this goal. @shubhamk008, I'm hoping this could take the pressure off of you to make full mockups soon, and get us just closer in the meantime.

We would make these CSS changes only for `xs` screens (up to 600px per [Material-UI](https://mui.com/material-ui/customization/breakpoints/#default-breakpoints)), either using `xs` classes or

```
@media (max-width: 600px) {
  /* … */
}
```

Currently we have:

![image](https://github.com/GeoDaCenter/chicago-environment-explorer/assets/10427268/deb60af5-da5d-4c3b-8801-a3f63208a8bf)

And the goal is something closer to:

![image](https://github.com/GeoDaCenter/chicago-environment-explorer/assets/10427268/7be08c7d-e4a1-4e9c-8257-fc64525240e4)
![image](https://github.com/GeoDaCenter/chicago-environment-explorer/assets/10427268/8c882e2a-f636-426d-b60a-3ab4d2150fbd)

The changes being:

1. Arrange the 2 main index builder sections in column instead of in row
2. Reduce padding on edges significantly and increase width of each section to fill screen
3. Center elements as needed

For the map page of the Index Builder, I think just making the panel collapsible would get us close enough for now.

![image](https://github.com/GeoDaCenter/chicago-environment-explorer/assets/10427268/ef7dd025-2a3a-4b21-95fa-9784b5b4f452)
